package com.thatsimpletech.assist.core.wire

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * core/src/test/resources/tstd-protocol-fixtures.json is a verbatim copy of
 * TST-Desk ui/src/lib/protocol-fixtures.json at commit b3f88d4, generated by
 * TST-Desk core/scripts/generate_protocol_fixtures.py: one `model_dump_json()` sample per
 * protocol message (client messages and daemon events both, 137 keys), plus `hello_ack`
 * built as a plain dict (generate_protocol_fixtures.py:900-901). JSON has no comments, so
 * the provenance lives here.
 */
object Fixtures {
    val all: Map<String, JsonObject> by lazy {
        val text = Fixtures::class.java.getResourceAsStream("/tstd-protocol-fixtures.json")!!
            .bufferedReader().use { it.readText() }
        Json.parseToJsonElement(text).jsonObject.mapValues { it.value.jsonObject }
    }

    fun kind(name: String): String = all.getValue(name)["type"]!!.jsonPrimitive.content

    fun text(name: String): String = all.getValue(name).toString()
}
